config/routes.rb
Rails.application.routes.draw do
  resources :photos

  get 'profiles/show'
  get '/:id', to: 'profiles#show'

  get 'courses/index'
  get 'reports/index'

  root 'photos#index'


  devise_for :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
  has_many :photos
end

app/models/photo.rb
class Photo < ApplicationRecord
  belongs_to :user
  belongs_to :course
  has_attached_file :image, styles: { medium: "300x300>"}

  validates :title, :image, presence:true
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  # validates_attachment_size :image, :in =>  0..1.megabytes 
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :photos

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true
  validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!, except: [:index, :show]
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
    def configure_permitted_parameters
     devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    end
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  def index
    @courses = Course.all
  end

  def new
    @course = Course.new
  end

  def create
    @course = Course.create(courses_params)

  end

  private
    def courses_params
      params.require(:course).permit(:name, :name_course)
    end
end

app/controllers/photos_controller.rb
class PhotosController < ApplicationController
  def index
    @photos = Photo.includes(:user, :course).all.order(created_at: :desc)

    if params[:user_id].present?
      @photos = @photos.where("user_id = ?", params[:user_id])
    end

    if params[:course_id].present?
      @photos = @photos.where("course_id = ?", params[:course_id])
    end
  end

  def new
    @photo = Photo.new
  end

  def create
    @photo = current_user.photos.create(photos_params)

    if @photo.save
      redirect_to root_path, notice: "La Evidencia fue creada con exito"
    else
      flash[:alert] = @photo.errors.full_messages
      render :new
    end
  end

  def show
    @photo = Photo.find(params[:id])
  end

  def edit
    @photo = Photo.find(params[:id])

    unless signed_in? && @photo.user == current_user
      redirect_to root_path
    end
  end

  def update
    @photo = Photo.find(params[:id])
    if @photo.update(photos_params)
      redirect_to photos_path, notice: "La evidencia se ha modificado con exito"
    else
      render :edit
    end
  end

  def destroy
    photo = Photo.find(params[:id])
    photo.destroy
    redirect_to photos_path, notice: "la evidencia se ha eliminado"
  end

  private
    def photos_params
      params.require(:photo).permit(:title, :image, :course_id)
    end
end

app/controllers/profiles_controller.rb
class ProfilesController < ApplicationController
  def show
    @user = User.find_by_name(params[:id])

    unless @user
      redirect_to root_path
    end
  end
end

app/controllers/reports_controller.rb
class ReportsController < ApplicationController
  def index
    @photos = Photo.includes(:user, :course).all
    @users_esp = User.includes(:photos).where(componet:"especifico")
    @users_trans = User.includes(:photos).where(componet:"transversal")
    respond_to do |format|
      format.html
      format.pdf  do
        render pdf: "reporte",
               template: "reports/index.pdf.erb",
               layout: "pdf.html.erb"
               # orientation: 'Landscape'
      end
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/photos_helper.rb
module PhotosHelper
end

app/helpers/profiles_helper.rb
module ProfilesHelper
end

app/helpers/reports_helper.rb
module ReportsHelper
end

app/views/courses/index.html.erb
<h1>Courses#index</h1>
<p>Find me in app/views/courses/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Photos</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Oxygen:400,700" rel="stylesheet">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'partials/navbar' %>

    <% if flash[:notice] %>
      <div class="alert alert-primary" role="alert" >
        <%= flash[:notice] %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% elsif flash[:alert] %>
      <div class="alert alert-danger alert-dismissible fade show" role="alert">
        <%= flash[:alert] %>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    <% end %>

    <%= yield %>
  </body>
</html>

app/views/layouts/pdf.html.erb
<!DOCTYPE html>
<html lang="es">
  <head>
    <meta charset="utf-8">
    <%= wicked_pdf_stylesheet_link_tag "pdf" -%>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <title></title>
  </head>
  <body>
    <%= yield %>
  </body>
</html>

app/views/partials/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
  <div class="container-fluid">
    <a class="navbar-brand" href="/"><b>Photos</b></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Instructores
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdown">
            <% User.all.each do |user| %>
              <%= link_to user.name, user.name, class:"dropdown-item" %>
            <% end %>
          </div>
        </li>
        <li class="nav-item">
          <% if signed_in? %>
            <div class="col-sm-2">
              <%= link_to "Nueva Foto", new_photo_path, class: "btn btn-outline-danger " %>
            </div>
          <% end %>
        </li>
      </ul>
      <ul class="navbar-nav">
        <% if signed_in? %>
          <li class="nav-item ">
            <%= link_to current_user.email , current_user.name, class: "nav-link"%>
          </li>
          <li class="nav-item ">
            <%= link_to "Salir" , destroy_user_session_path, method: :delete, class: "nav-link"%>
          </li>
        <% else %>
          <li class="nav-item ">
            <%= link_to "Ingresar" , new_user_session_path, class: "nav-link"%>
          </li>
          <li class="nav-item ">
            <%= link_to "Registrarse" , new_user_registration_path, class: "nav-link"%>
          </li>
        <% end %>

    </div>
  </div>
</nav>

app/views/photos/edit.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-sm-4">
      <p><%= link_to '<i class="material-icons">reply_all</i> Volver'.html_safe, root_path %></p>
      <h1>Nueva Evidencia</h1>
      <%= form_for @photo do |f|%>
        <div class="form-group">
          <%= f.text_field :title, placeholder: "Ingresa el titulo de la actividad", class: "form-control"%>
        </div>

        <div class="form-group">
          <%= f.file_field :image %>
        </div>

        <div class="form-group">
          <%= f.collection_select :course_id, Course.all, :id, :name %>
        </div>

        <div class="form-group">
          <%= f.submit "Publicar", class: "btn btn-primary btn-block"%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/photos/index.html.erb
<div class="container-fluid">
  <div class="row justify-content-around start">
    <div class="col-sm-7 col-md-9">
      <h1>Evidencias Fotograficas POLI-SENA 2018</h1>
    </div>
    <div class="col-sm-4 col-md-2">
      <%= form_tag photos_path, method: :get do %>
      <div class="form-group">
        <%= select_tag :user_id, options_from_collection_for_select(User.all, "id", "name", params[:user_id]), prompt: "Instructor", class: "form-control form-control-sm" %>
      </div>
      <div class="form-group">
        <%= select_tag :course_id, options_from_collection_for_select(Course.all, "id", "name", params[:course_id]), prompt: "Ficha", class: "form-control form-control-sm" %>
      </div>
      <%= submit_tag "Buscar", name: nil, class: "btn-color btn btn-dark btn-sm btn-block" %>
      <% end %>
    </div>
  </div>


  <div class="row justify-content-around">
    <% @photos.each do |photo| %>
      <div class="card card-shadow card-margin" style="width: 15rem;">
        <%= image_tag photo.image.url(:medium), class:"card-img-top img_size_index" %>
        <div class="card-body">
          <p class="card-text"><%= photo.title %></p>
          <p>Ficha: <b><%= photo.course.name %></b></p>
          <p class="font-italic text-secondary">Publicado por <b><%= link_to photo.user.name, photo.user.name %></b>, <%= time_ago_in_words(photo.created_at) %></p>
          <% if signed_in? && photo.user == current_user %>
            <div class="text-right">
              <%= link_to 'Editar <i class="material-icons">create</i>'.html_safe, edit_photo_path(photo) %>
              <%= link_to 'Eliminar <i class="material-icons">delete_sweep</i>'.html_safe, photo, method: :delete, data: { confirm: "¿Estás seguro de eliminar esta evidencia?" } %>
            </div>
          <% end %>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/photos/new.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-xs-8 col-sm-6 card card-shadow">
      <p><%= link_to '<i class="material-icons">reply_all</i> Volver'.html_safe, root_path %></p>
      <h1>Nueva Evidencia</h1>
      <%= form_for @photo do |f|%>
        <div class="form-group">
          <%= f.text_field :title, placeholder: "Ingresa el titulo de la actividad", class: "form-control"%>
        </div>

        <div class="form-group">
          <%= f.label "la foto no puede ser mayor a 1MB." %>
          <%= f.file_field :image %>
        </div>

        <div class="form-group">
          <%= link_to "si supero este tamaño redimencionala aqui", "http://webresizer.com/resizer/", target:"_blank", class:"font-italic" %>
        </div>

        <div class="form-group">
          <%= f.collection_select :course_id, Course.all, :id, :name %>
        </div>

        <div class="form-group">
          <%= f.submit "Publicar", class: "btn btn-dark btn-block btn-color"%>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/photos/show.html.erb
<div class="container">
  <div class="row justify-content-center">
    <div class="col-sm-10">
      <h1>Evidencia</h1>
      <div class="card card-shadow card-margin" style="width: 35rem;">
        <%= image_tag @photo.image.url(:medium), class:"card-img-top" %>
        <div class="card-body">
          <p class="card-text"><%= @photo.title %></p>
        </div>
        <br>
      </div>
    </div>
  </div>
</div>

app/views/profiles/show.html.erb
<div class="container-fluid profiles">
  <div class="row justify-content-start">
    <div class="col-sm-10 profiles__header">
      <h1><%= @user.name %></h1>
      <h2><%= @user.email %></h2>
    </div>
  </div>
  <div class="row justify-content-around">
    <% @user.photos.each do |photo| %>
      <div class="card card-shadow card-margin" style="width: 25rem;">
        <%= image_tag photo.image.url(:medium), class:"card-img-top profiles__card--img" %>
        <div class="card-body">
          <p class="card-text"><%= photo.title %></p>
          <p>Ficha: <b><%= photo.course.name %></b>,  <%= time_ago_in_words(photo.created_at) %></p>
          <% if signed_in? && photo.user == current_user %>
            <div class="text-left">
              <%= link_to 'Editar <i class="material-icons">create</i>'.html_safe, edit_photo_path(photo) %>
              <%= link_to 'Eliminar <i class="material-icons">delete_sweep</i>'.html_safe, photo, method: :delete, data: { confirm: "¿Estás seguro de eliminar esta evidencia?" } %>
            </div>
          <% end %>
        </div>
        <br>
      </div>
    <% end %>
  </div>
  <p><%= link_to '<i class="material-icons">reply_all</i> Volver'.html_safe, root_path %></p>
</div>

app/views/reports/index.html.erb
<div class="container">
  <h1>reporte</h1>
  <div class="row justify-content-around">
    <% @users_esp.each do |user| %>
      <% user.photos.each do |photo| %>
        <div class="card" style="margin-bottom:20px">
          <div class="card-body">
            <p class="card-title">Programa: <%= photo.course.name_course %></p>
            <p>Ficha: <%= photo.course.name %></p>
            <%= image_tag photo.image.url(:medium), class:"card-img-top cel_img" %>
            <p class="card-text"><small class="text-muted">Componente: <%= user.componet %></small></p>
            <p class="card-text"><small class="text-muted"> Instructor: <%= user.name %></small></p>
            <p class="card-text"><small class="text-muted">Fecha: <%= photo.created_at %></small></p>
          </div>
        </div>
      <%end%>
    <%end%>
  </div>
</div>


<!-- <div class="container-fluid">
  <h1>reportes</h1>
  <div class="row justify-content-center">
    <div class="col-md-10">
      <table class="table">
        <thead>
          <tr>
            <th>
              <% @users_esp.each do |user| %>
                <% user.photos.each do |photo| %>
                    Programa: <%= photo.course.name_course %><br>
                    Ficha: <%= photo.course.name %>
                <%end%>
              <%end%>
            </th>
            <th>
              <% @users_trans.each do |user| %>
                <% user.photos.each do |photo| %>
                    Programa: <%= photo.course.name_course %><br>
                    Ficha: <%= photo.course.name %>
                <%end%>
              <%end%>
            </th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>
              <% @users_esp.each do |user| %>
                <% user.photos.each do |photo| %>
                  <%= image_tag photo.image.url(:medium), class:"cel_img" %>
                <%end%>
              <%end%>
            </td>
            <td>
              <% @users_trans.each do |user| %>
                <% user.photos.each do |photo| %>
                  <%= image_tag photo.image.url(:medium), class:"cel_img" %>
                <%end%>
              <%end%>
            </td>
          </tr>
          <tr>
            <td>
              <% @users_esp.each do |user| %>
                <% user.photos.each do |photo| %>
                  Componente: <%= user.componet %><br>
                  Instructor: <%= user.name %><br>
                  Fecha: <%= photo.created_at %>
                <%end%>
              <%end%>
            </td>
            <td>
              <% @users_trans.each do |user| %>
                <% user.photos.each do |photo| %>
                  Componente: <%= user.componet %><br>
                  Instructor: <%= user.name %><br>
                  Fecha: <%= photo.created_at %>
                <%end%>
              <%end%>
            </td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
</div> -->

app/views/reports/index.pdf.erb
<div class="container">
  <h1>reporte</h1>
  <% @users_esp.each do |user| %>
    <% @users_trans.each do |trans| %>
      <% user.photos.each do |photo| %>
        <% trans.photos.each do |photo_trans| %>
          <table class="table">
            <tbody>
              <tr>
                <td>
                  Programa: <%= photo.course.name_course %><br>
                  Ficha: <%= photo.course.name %><br>
                  Titulo: <%= photo.title %>
                </td>
                <td>
                  Programa: <%= photo_trans.course.name_course %><br>
                  Ficha: <%= photo_trans.course.name %><br>
                  Titulo: <%= photo_trans.title %>
                </td>
              </tr>
              <tr>
                <td>
                  <%= wicked_pdf_image_tag photo.image.url(:medium), class:"cel_img" %>
                </td>
                <td>
                  <%= wicked_pdf_image_tag photo_trans.image.url(:medium), class:"cel_img" %>
                </td>
              </tr>
              <tr>
                <td>
                  Componente: <%= user.componet %><br>
                  Instructor: <%= user.name %><br>
                  Fecha: <%= photo.created_at %>
                </td>
                <td>
                  Componente: <%= trans.componet %><br>
                  Instructor: <%= trans.name %><br>
                  Fecha: <%= photo_trans.created_at %>
                </td>
              </tr>
            </tbody>
          </table>
          <br><br><br>
        <%end%>
      <%end%>
    <%end%>
  <%end%>
</div>

<!-- <div class="container">
  <h1>reporte</h1>
  <div class="row justify-content-around">
    <% @users_esp.each do |user| %>
      <% user.photos.each do |photo| %>
        <div class="card card_pdf" style="margin-bottom:20px">
          <div class="card-body">
            <p class="card-title">Programa: <%= photo.course.name_course %></p>
            <p>Ficha: <%= photo.course.name %></p>
            <%= wicked_pdf_image_tag photo.image.url(:medium), class:"card-img-top cel_img" %>
            <p class="card-text"><small class="text-muted">Componente: <%= user.componet %></small></p>
            <p class="card-text"><small class="text-muted"> Instructor: <%= user.name %></small></p>
            <p class="card-text"><small class="text-muted">Fecha: <%= photo.created_at %></small></p>
          </div>
        </div>
      <%end%>
    <%end%>
  </div>
</div> -->

<!-- <div class="container-fluid">
  <h1>reportes</h1>
  <div class="row justify-content-around">
    <div class="col-sm-4 col-md-4">
      <% @users_esp.each do |user| %>
        <% user.photos.each do |photo| %>
          <table class="table table_pdf">
            <thead>
              <tr>
                <th>
                  Programa: <%= photo.course.name_course %><br>
                  Ficha: <%= photo.course.name %>
                </th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><%= wicked_pdf_image_tag photo.image.url(:medium), class:"cel_img" %></td>
              </tr>
              <tr>
                <td>
                  Componente: <%= user.componet %><br>
                  Instructor: <%= user.name %><br>
                  Fecha: <%= photo.created_at %>
                </td>
              </tr>
            </tbody>
          </table>
        <% end %>
      <% end %>
    </div>

    <div class="col-sm-4 col-md-4">
      <% @users_trans.each do |trans| %>
        <% trans.photos.each do |photo| %>
          <table class="table table_pdf">
            <thead>
              <tr>
                <th>
                  Programa: <%= photo.course.name_course %><br>
                  Ficha: <%= photo.course.name %>
                </th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td><%= wicked_pdf_image_tag photo.image.url(:medium), class:"cel_img" %></td>
              </tr>
              <tr>
                <td>
                  Componente: <%= trans.componet %><br>
                  Instructor: <%= trans.name %><br>
                  Fecha: <%= photo.created_at %>
                </td>
              </tr>
            </tbody>
          </table>
        <% end %>
      <% end %>
    </div>
  </div>
</div> -->